MSA_ALIGNMENT_FILE /Users/mqbssdt7/Dropbox/temp/VIRUS_COEVOLUTION/DATA/HIV/GP120/PROCESSED/subtype_B.phy
TREE_FILE /Users/mqbssdt7/Dropbox/temp/VIRUS_COEVOLUTION/DATA/HIV/GP120/PROCESSED/subtype_B.newick
OUTPUT_FILE /Users/mqbssdt7/Dropbox/temp/VIRUS_COEVOLUTION/RESULTS/HIV/GP120/SUBTYPE_B/subtype_B_mps_test2
#PAIRS_FILE /Users/mqbssdt7/Dropbox/temp/VIRUS_COEVOLUTION/RESULTS/HIV/GP120/SUBTYPE_B/pairs.tab
